# Compiles the main.tex file and returns the PDF.
@compile:
  docker run --rm -v "$(pwd):/workspace" latex-env sh -c "latexmk -pdf main.tex && latexmk -c"
  # docker run --rm -v "$(pwd):/workspace" latex-env pdflatex main.tex
